\doxysection{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Protocol\+Error Class Reference}
\hypertarget{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1ProtocolError}{}\label{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1ProtocolError}\index{pip.\_vendor.urllib3.exceptions.ProtocolError@{pip.\_vendor.urllib3.exceptions.ProtocolError}}


Inheritance diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Protocol\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Protocol\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when something unexpected happens mid-request/response.\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__vendor_2urllib3_2exceptions_8py_source_l00064}{64}} of file \mbox{\hyperlink{pip_2__vendor_2urllib3_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+vendor/urllib3/exceptions.\+py\end{DoxyCompactItemize}
