\doxysection{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error Class Reference}
\hypertarget{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError}{}\label{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError}\index{pip.\_vendor.urllib3.exceptions.TimeoutError@{pip.\_vendor.urllib3.exceptions.TimeoutError}}


Inheritance diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when a socket timeout error occurs.

Catching this error will catch both :exc:`ReadTimeoutErrors
<ReadTimeoutError>` and :exc:`ConnectTimeoutErrors <ConnectTimeoutError>`.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__vendor_2urllib3_2exceptions_8py_source_l00110}{110}} of file \mbox{\hyperlink{pip_2__vendor_2urllib3_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+vendor/urllib3/exceptions.\+py\end{DoxyCompactItemize}
