\doxysection{numpy.\+linalg.\+linalg.\+Lin\+Alg\+Error Class Reference}
\hypertarget{classnumpy_1_1linalg_1_1linalg_1_1LinAlgError}{}\label{classnumpy_1_1linalg_1_1linalg_1_1LinAlgError}\index{numpy.linalg.linalg.LinAlgError@{numpy.linalg.linalg.LinAlgError}}


Inheritance diagram for numpy.\+linalg.\+linalg.\+Lin\+Alg\+Error\+:
% FIG 0


Collaboration diagram for numpy.\+linalg.\+linalg.\+Lin\+Alg\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Generic Python-exception-derived object raised by linalg functions.

General purpose exception class, derived from Python's ValueError
class, programmatically raised in linalg functions when a Linear
Algebra-related condition would prevent further correct execution of the
function.

Parameters
----------
None

Examples
--------
>>> from numpy import linalg as LA
>>> LA.inv(np.zeros((2,2)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...linalg.py", line 350,
    in inv return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
  File "...linalg.py", line 249,
    in solve
    raise LinAlgError('Singular matrix')
numpy.linalg.LinAlgError: Singular matrix
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{numpy_2linalg_2linalg_8py_source_l00068}{68}} of file \mbox{\hyperlink{numpy_2linalg_2linalg_8py_source}{linalg.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/numpy/linalg/linalg.\+py\end{DoxyCompactItemize}
