\doxysection{pip.\+\_\+internal.\+exceptions.\+Bad\+Command Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1BadCommand}{}\label{classpip_1_1__internal_1_1exceptions_1_1BadCommand}\index{pip.\_internal.exceptions.BadCommand@{pip.\_internal.exceptions.BadCommand}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when virtualenv or a command is not found\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00279}{279}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
